#include <benchmark/benchmark.h>
//#include "FP/FPSqrt.h"
//#include "FP/FPReduce.h"
//#include "FP/FPAdd.h"
//#include "FP/FPSub.h"
//#include "FP/FPMul.h"
//#include "FP/FPDiv.h"
//#include "FP/FPGT.h"
//#include "FP/FPLT.h"
//#include "FP/FPEQ.h"
//#include "FP/FPIsZero.h"

//#include "Int/IntAdd.h"
//#include "Int/IntSub.h"
//#include "Int/IntMul.h"
//#include "Int/IntDiv.h"
//#include "Int/IntAnd.h"
//#include "Int/IntOr.h"
//#include "Int/IntXor.h"
//#include "Int/IntNot.h"
//#include "Int/IntGT.h"
//#include "Int/IntLT.h"
//#include "Int/IntEQ.h"
//#include "Int/IntIsZero.h"
//#include "Int/IntSL.h"
//#include "Int/IntSR.h"
//#include "Int/IntShuffle.h"

BENCHMARK_MAIN();
